### ISSUE TITLE
Remove duplicated CSS attributes

### ISSUE THREAD

**Issue by stevenmhunt** [stevenmhunt/badgerly#6]
There are places in the code where SCSS capabilities could be used to remove duplication.

**Comment by kushalpandya** [comment]
This may be due to the way SASS `@mixin`s are used, we can use `@extend` instead and reduce quite a lot of duplication. However, it would also add couple of extra classes which are directly not used in the markup. 

I'm proposing something like following.

``` scss
._circle {
  border-radius: 5px;
  font-size: 6px;
  text-align: center;
}
.badge.tiny {
  .circle, .circle.border {
    // @include circle;
    @extend ._circle;
    width: 10px;
    height: 8px;
    padding-top: 1px;
  }
}
```

Which results into something like

``` css
._circle,
.badge.tiny .circle,
.badge.tiny .circle.border {
  border-radius: 5px;
  font-size: 6px;
  text-align: center;
}

.badge.tiny .circle,
.badge.tiny .circle.border {
  width: 10px;
  height: 8px;
  padding-top: 1px;
}
```

Which just prevented `border-radius`, `font-size` and `text-align` properties from being duplicated in generated CSS. Although my concern is only about extra `._circle` class, may be we can have better property distribution which won't lead to extra unused classes. Let me know what you think.
